# -*- coding: utf-8 -*-
"""monitor_visual_3d_integracion_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJa_jWX0RtWNwBlmnQQQqMFm4Q2DsWea
"""

import socket
import json
import time
import numpy as np
import random 

HOST = '127.0.0.1'  
PORT = 65432        

print(f"Iniciando servidor de sockets en {HOST}:{PORT}...")

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind((HOST, PORT))
server_socket.listen(1) 
print("Esperando conexión de un cliente 3D...")

conn = None
addr = None

try:
    conn, addr = server_socket.accept()
    print(f"Conectado por: {addr}")
    print("Conexión establecida. Preparado para enviar datos simulados.")

except Exception as e:
    print(f"Error al iniciar el servidor o aceptar conexión: {e}")
    if server_socket:
        server_socket.close()

if conn:
    current_x = 0.0
    current_y = 0.0
    direction_x = 1 
    direction_y = 1 
    max_coord = 50.0
    min_coord = -50.0

    try:
        while True:
            num_people = random.randint(0, 10)

            move_speed = 1.0 + random.uniform(-0.5, 0.5) 
            current_x += direction_x * move_speed
            current_y += direction_y * move_speed

            if current_x > max_coord or current_x < min_coord:
                direction_x *= -1
                current_x = max(min_coord, min(max_coord, current_x)) 

            if current_y > max_coord or current_y < min_coord:
                direction_y *= -1
                current_y = max(min_coord, min(max_coord, current_y)) 

            data_to_send = {
                "num_people": num_people,
                "object_position": {
                    "x": round(current_x, 2),
                    "y": round(current_y, 2),
                    "z": 0.0 #
                },
                "timestamp": time.strftime("%H:%M:%S")
            }

            json_data = json.dumps(data_to_send)
            message = (json_data + '\n').encode('utf-8')

            conn.sendall(message)
            print(f"Enviado: {json_data}")

            time.sleep(0.5) 
    except BrokenPipeError:
        print("El cliente 3D se desconectó inesperadamente.")
    except Exception as e:
        print(f"Error durante el envío de datos: {e}")
    finally:
        if conn:
            conn.close()
            print("Conexión cerrada.")
        if server_socket:
            server_socket.close()
            print("Servidor de sockets cerrado.")
else:
    print("No hay conexión establecida para enviar datos.")